// SheLeads — Opportunity Dataset (100+ items)

export const SKILLS_LIST = [
  // Tech
  "JavaScript", "React", "Python", "Java", "C++", "C#", "TypeScript",
  "Node.js", "HTML/CSS", "SQL", "MongoDB", "Firebase", "AWS", "Docker",
  "Machine Learning", "Data Science", "TensorFlow", "Computer Vision",
  "Cybersecurity", "Blockchain", "Flutter", "Swift", "Kotlin", "Unity",
  "REST APIs", "GraphQL", "Git", "Linux", "DevOps", "Cloud Computing",
  // Business
  "Marketing", "Finance", "Accounting", "Business Development",
  "Project Management", "Product Management", "Strategy", "Sales",
  "Operations", "Entrepreneurship", "Leadership", "Public Speaking",
  "Business Analytics", "Excel", "PowerPoint", "Market Research",
  // Design
  "UI/UX Design", "Figma", "Adobe XD", "Photoshop", "Illustrator",
  "Graphic Design", "Motion Graphics", "Branding", "Typography",
  "3D Modeling", "Canva", "Video Editing", "Photography",
  // Research & Academia
  "Research", "Data Analysis", "Statistics", "Writing", "Editing",
  "Content Creation", "Social Media", "SEO", "Communication",
  "Critical Thinking", "Problem Solving", "Teamwork",
  // Other
  "Other"
];

export const opportunities = [
  // INTERNSHIPS
  { id: 1, title: "Google STEP Internship", type: "Internship", org: "Google", skills: ["Python", "Java", "Data Structures", "Algorithms"], deadline: "2025-12-01", stipend: "$8,000/mo", location: "Remote/US" },
  { id: 2, title: "Microsoft SWE Intern", type: "Internship", org: "Microsoft", skills: ["C#", "JavaScript", "Azure", "TypeScript"], deadline: "2025-11-15", stipend: "$7,500/mo", location: "Redmond, WA" },
  { id: 3, title: "Meta Product Intern", type: "Internship", org: "Meta", skills: ["Product Management", "Data Analysis", "SQL", "Strategy"], deadline: "2025-10-30", stipend: "$7,000/mo", location: "Menlo Park, CA" },
  { id: 4, title: "Goldman Sachs Finance Intern", type: "Internship", org: "Goldman Sachs", skills: ["Finance", "Excel", "Python", "Business Analytics"], deadline: "2025-09-30", stipend: "$6,500/mo", location: "New York, NY" },
  { id: 5, title: "Adobe Design Internship", type: "Internship", org: "Adobe", skills: ["UI/UX Design", "Figma", "Photoshop", "Illustrator"], deadline: "2025-11-01", stipend: "$5,500/mo", location: "San Jose, CA" },
  { id: 6, title: "Amazon SDE Intern", type: "Internship", org: "Amazon", skills: ["Java", "Python", "AWS", "Data Structures"], deadline: "2025-12-15", stipend: "$7,800/mo", location: "Seattle, WA" },
  { id: 7, title: "Netflix Data Science Intern", type: "Internship", org: "Netflix", skills: ["Python", "Machine Learning", "Statistics", "SQL"], deadline: "2025-10-15", stipend: "$8,500/mo", location: "Los Gatos, CA" },
  { id: 8, title: "Spotify UX Research Intern", type: "Internship", org: "Spotify", skills: ["Research", "UI/UX Design", "Statistics", "Communication"], deadline: "2025-11-20", stipend: "$4,500/mo", location: "Remote" },
  { id: 9, title: "Shopify Developer Intern", type: "Internship", org: "Shopify", skills: ["React", "Node.js", "JavaScript", "REST APIs"], deadline: "2025-10-01", stipend: "$5,000/mo", location: "Remote" },
  { id: 10, title: "Twitter/X ML Intern", type: "Internship", org: "Twitter/X", skills: ["Machine Learning", "Python", "TensorFlow", "Data Science"], deadline: "2025-09-15", stipend: "$7,200/mo", location: "San Francisco, CA" },
  { id: 11, title: "Stripe Backend Intern", type: "Internship", org: "Stripe", skills: ["Java", "Ruby", "REST APIs", "SQL"], deadline: "2025-11-30", stipend: "$8,000/mo", location: "Remote" },
  { id: 12, title: "Figma Product Design Intern", type: "Internship", org: "Figma", skills: ["UI/UX Design", "Figma", "Product Management", "Typography"], deadline: "2025-10-20", stipend: "$5,200/mo", location: "San Francisco, CA" },
  { id: 13, title: "Deloitte Consulting Intern", type: "Internship", org: "Deloitte", skills: ["Business Analytics", "Strategy", "Excel", "PowerPoint"], deadline: "2025-09-01", stipend: "$3,500/mo", location: "New York, NY" },
  { id: 14, title: "McKinsey Business Analyst Intern", type: "Internship", org: "McKinsey", skills: ["Strategy", "Market Research", "Business Development", "Communication"], deadline: "2025-08-15", stipend: "$4,000/mo", location: "Chicago, IL" },
  { id: 15, title: "Airbnb Growth Marketing Intern", type: "Internship", org: "Airbnb", skills: ["Marketing", "SEO", "Data Analysis", "Content Creation"], deadline: "2025-10-10", stipend: "$4,800/mo", location: "Remote" },
  { id: 16, title: "Salesforce CRM Intern", type: "Internship", org: "Salesforce", skills: ["Sales", "Business Development", "CRM", "Communication"], deadline: "2025-11-05", stipend: "$4,200/mo", location: "San Francisco, CA" },
  { id: 17, title: "Tesla Embedded Systems Intern", type: "Internship", org: "Tesla", skills: ["C++", "Python", "Linux", "DevOps"], deadline: "2025-12-20", stipend: "$6,000/mo", location: "Austin, TX" },
  { id: 18, title: "Palantir SWE Intern", type: "Internship", org: "Palantir", skills: ["Python", "Java", "SQL", "Data Science"], deadline: "2025-10-25", stipend: "$7,000/mo", location: "Denver, CO" },
  { id: 19, title: "Canva Graphic Design Intern", type: "Internship", org: "Canva", skills: ["Graphic Design", "Canva", "Branding", "Marketing"], deadline: "2025-09-20", stipend: "$3,000/mo", location: "Remote" },
  { id: 20, title: "ByteDance AI Intern", type: "Internship", org: "ByteDance", skills: ["Machine Learning", "Python", "Computer Vision", "TensorFlow"], deadline: "2025-11-10", stipend: "$9,000/mo", location: "Mountain View, CA" },
  { id: 21, title: "Uber Data Engineering Intern", type: "Internship", org: "Uber", skills: ["SQL", "Python", "Data Science", "Cloud Computing"], deadline: "2025-10-05", stipend: "$6,800/mo", location: "San Francisco, CA" },
  { id: 22, title: "LinkedIn Social Media Intern", type: "Internship", org: "LinkedIn", skills: ["Social Media", "Content Creation", "Marketing", "Writing"], deadline: "2025-09-10", stipend: "$3,800/mo", location: "Remote" },
  { id: 23, title: "HubSpot Content Marketing Intern", type: "Internship", org: "HubSpot", skills: ["Content Creation", "SEO", "Writing", "Marketing"], deadline: "2025-10-15", stipend: "$2,800/mo", location: "Remote" },
  { id: 24, title: "Notion Product Intern", type: "Internship", org: "Notion", skills: ["Product Management", "UI/UX Design", "Strategy", "Writing"], deadline: "2025-11-25", stipend: "$5,500/mo", location: "Remote" },
  { id: 25, title: "Zoom Frontend Intern", type: "Internship", org: "Zoom", skills: ["React", "JavaScript", "HTML/CSS", "TypeScript"], deadline: "2025-10-30", stipend: "$5,000/mo", location: "Remote" },

  // JOBS
  { id: 26, title: "Junior Frontend Developer", type: "Job", org: "TechCorp Inc.", skills: ["React", "JavaScript", "HTML/CSS", "Git"], deadline: "2025-08-30", stipend: "$75K/yr", location: "Remote" },
  { id: 27, title: "Data Analyst", type: "Job", org: "DataVision", skills: ["SQL", "Python", "Data Analysis", "Excel"], deadline: "2025-09-05", stipend: "$65K/yr", location: "New York, NY" },
  { id: 28, title: "UX Designer", type: "Job", org: "DesignStudio", skills: ["UI/UX Design", "Figma", "Adobe XD", "Research"], deadline: "2025-09-15", stipend: "$80K/yr", location: "Remote" },
  { id: 29, title: "Marketing Manager", type: "Job", org: "BrandWave", skills: ["Marketing", "SEO", "Content Creation", "Social Media"], deadline: "2025-08-20", stipend: "$70K/yr", location: "Austin, TX" },
  { id: 30, title: "ML Engineer", type: "Job", org: "AI Ventures", skills: ["Machine Learning", "Python", "TensorFlow", "Data Science"], deadline: "2025-10-01", stipend: "$120K/yr", location: "Remote" },
  { id: 31, title: "Product Manager", type: "Job", org: "StartupX", skills: ["Product Management", "Strategy", "Data Analysis", "Leadership"], deadline: "2025-09-25", stipend: "$100K/yr", location: "San Francisco, CA" },
  { id: 32, title: "Backend Developer", type: "Job", org: "CloudBase", skills: ["Node.js", "Python", "AWS", "Docker"], deadline: "2025-10-10", stipend: "$90K/yr", location: "Remote" },
  { id: 33, title: "Cybersecurity Analyst", type: "Job", org: "SecureNet", skills: ["Cybersecurity", "Linux", "Python", "Networking"], deadline: "2025-09-30", stipend: "$95K/yr", location: "Washington, DC" },
  { id: 34, title: "Financial Analyst", type: "Job", org: "CapitalGroup", skills: ["Finance", "Excel", "Accounting", "Business Analytics"], deadline: "2025-08-25", stipend: "$72K/yr", location: "Chicago, IL" },
  { id: 35, title: "Content Strategist", type: "Job", org: "MediaPulse", skills: ["Content Creation", "Writing", "SEO", "Social Media"], deadline: "2025-09-20", stipend: "$55K/yr", location: "Remote" },
  { id: 36, title: "DevOps Engineer", type: "Job", org: "InfraScale", skills: ["Docker", "AWS", "Linux", "DevOps"], deadline: "2025-10-20", stipend: "$110K/yr", location: "Remote" },
  { id: 37, title: "Business Development Rep", type: "Job", org: "GrowthLabs", skills: ["Sales", "Business Development", "Communication", "CRM"], deadline: "2025-09-01", stipend: "$60K/yr", location: "Boston, MA" },
  { id: 38, title: "Graphic Designer", type: "Job", org: "CreativeHive", skills: ["Graphic Design", "Illustrator", "Photoshop", "Branding"], deadline: "2025-08-15", stipend: "$58K/yr", location: "Remote" },
  { id: 39, title: "Full Stack Developer", type: "Job", org: "WebForge", skills: ["React", "Node.js", "MongoDB", "REST APIs"], deadline: "2025-10-05", stipend: "$85K/yr", location: "Remote" },
  { id: 40, title: "Research Scientist", type: "Job", org: "ResearchLab", skills: ["Research", "Python", "Statistics", "Machine Learning"], deadline: "2025-11-01", stipend: "$98K/yr", location: "Cambridge, MA" },
  { id: 41, title: "Operations Manager", type: "Job", org: "OpsFirst", skills: ["Operations", "Project Management", "Leadership", "Excel"], deadline: "2025-09-12", stipend: "$78K/yr", location: "Atlanta, GA" },
  { id: 42, title: "Motion Designer", type: "Job", org: "AnimateX", skills: ["Motion Graphics", "Illustrator", "Video Editing", "Adobe XD"], deadline: "2025-10-15", stipend: "$68K/yr", location: "Remote" },
  { id: 43, title: "Cloud Architect", type: "Job", org: "CloudPeak", skills: ["AWS", "Cloud Computing", "Docker", "DevOps"], deadline: "2025-11-15", stipend: "$130K/yr", location: "Remote" },
  { id: 44, title: "Social Media Manager", type: "Job", org: "ViralHive", skills: ["Social Media", "Content Creation", "Marketing", "Photography"], deadline: "2025-09-08", stipend: "$52K/yr", location: "Remote" },
  { id: 45, title: "Data Engineer", type: "Job", org: "DataPipeline Co.", skills: ["Python", "SQL", "AWS", "Data Science"], deadline: "2025-10-25", stipend: "$105K/yr", location: "Remote" },
  { id: 46, title: "iOS Developer", type: "Job", org: "AppCraft", skills: ["Swift", "Xcode", "REST APIs", "UI/UX Design"], deadline: "2025-09-22", stipend: "$92K/yr", location: "Austin, TX" },
  { id: 47, title: "Technical Writer", type: "Job", org: "DocuTech", skills: ["Writing", "Communication", "Research", "HTML/CSS"], deadline: "2025-08-28", stipend: "$62K/yr", location: "Remote" },
  { id: 48, title: "Blockchain Developer", type: "Job", org: "CryptoBuilders", skills: ["Blockchain", "JavaScript", "Python", "Cybersecurity"], deadline: "2025-11-20", stipend: "$115K/yr", location: "Remote" },
  { id: 49, title: "HR Analyst", type: "Job", org: "PeopleFirst", skills: ["Business Analytics", "Excel", "Communication", "Statistics"], deadline: "2025-09-14", stipend: "$58K/yr", location: "Dallas, TX" },
  { id: 50, title: "Game Developer", type: "Job", org: "PixelForge", skills: ["Unity", "C#", "3D Modeling", "JavaScript"], deadline: "2025-10-18", stipend: "$78K/yr", location: "Remote" },

  // HACKATHONS
  { id: 51, title: "HackHER 2025", type: "Hackathon", org: "WomenInTech", skills: ["JavaScript", "React", "Problem Solving", "Teamwork"], deadline: "2025-08-10", stipend: "$10,000 prize", location: "Online" },
  { id: 52, title: "MLH Global Hack Week", type: "Hackathon", org: "Major League Hacking", skills: ["Python", "APIs", "Machine Learning", "Problem Solving"], deadline: "2025-08-15", stipend: "$5,000 prize", location: "Online" },
  { id: 53, title: "Google Women Techmakers Hackathon", type: "Hackathon", org: "Google", skills: ["Flutter", "Firebase", "React", "UI/UX Design"], deadline: "2025-09-01", stipend: "$15,000 prize", location: "Online" },
  { id: 54, title: "FinTech Futures Hackathon", type: "Hackathon", org: "FinTechHub", skills: ["Finance", "Blockchain", "Python", "React"], deadline: "2025-08-20", stipend: "$8,000 prize", location: "New York, NY" },
  { id: 55, title: "Climate Tech Challenge", type: "Hackathon", org: "EarthHacks", skills: ["Data Science", "Python", "Research", "Problem Solving"], deadline: "2025-09-10", stipend: "$12,000 prize", location: "Online" },
  { id: 56, title: "AI for Good Hackathon", type: "Hackathon", org: "TechForHumanity", skills: ["Machine Learning", "Python", "TensorFlow", "Problem Solving"], deadline: "2025-08-25", stipend: "$20,000 prize", location: "San Francisco, CA" },
  { id: 57, title: "Design Thinking Sprint", type: "Hackathon", org: "IDEO", skills: ["UI/UX Design", "Figma", "Problem Solving", "Teamwork"], deadline: "2025-09-05", stipend: "$6,000 prize", location: "Online" },
  { id: 58, title: "Health Innovate Hackathon", type: "Hackathon", org: "MedTechOrg", skills: ["Data Analysis", "Python", "Research", "Machine Learning"], deadline: "2025-09-20", stipend: "$25,000 prize", location: "Online" },
  { id: 59, title: "CyberShield Challenge", type: "Hackathon", org: "SANS Institute", skills: ["Cybersecurity", "Linux", "Python", "Networking"], deadline: "2025-08-30", stipend: "$9,000 prize", location: "Online" },
  { id: 60, title: "Social Good Hack", type: "Hackathon", org: "NonprofitTech", skills: ["React", "Node.js", "UI/UX Design", "Problem Solving"], deadline: "2025-09-15", stipend: "$7,500 prize", location: "Online" },
  { id: 61, title: "Web3 Buildathon", type: "Hackathon", org: "ETHGlobal", skills: ["Blockchain", "JavaScript", "Solidity", "React"], deadline: "2025-10-01", stipend: "$30,000 prize", location: "Online" },
  { id: 62, title: "Open Source Sprint", type: "Hackathon", org: "GitHubUniverse", skills: ["Git", "JavaScript", "Python", "Problem Solving"], deadline: "2025-09-28", stipend: "$5,500 prize", location: "Online" },
  { id: 63, title: "EdTech Innovation Hack", type: "Hackathon", org: "LearnX", skills: ["React", "Node.js", "UI/UX Design", "Product Management"], deadline: "2025-10-08", stipend: "$10,000 prize", location: "Online" },
  { id: 64, title: "SheBuilds Mobile Hackathon", type: "Hackathon", org: "SheTech", skills: ["Flutter", "Swift", "Kotlin", "UI/UX Design"], deadline: "2025-10-15", stipend: "$8,000 prize", location: "Online" },
  { id: 65, title: "Data for Democracy Hack", type: "Hackathon", org: "CivicTech", skills: ["Data Science", "Python", "Data Analysis", "Statistics"], deadline: "2025-10-22", stipend: "$11,000 prize", location: "Online" },
  { id: 66, title: "AgriTech Challenge", type: "Hackathon", org: "FoodTechOrg", skills: ["Machine Learning", "Python", "IoT", "Data Analysis"], deadline: "2025-11-01", stipend: "$15,000 prize", location: "Online" },
  { id: 67, title: "GameJam 2025", type: "Hackathon", org: "IndieGameDev", skills: ["Unity", "C#", "3D Modeling", "Game Design"], deadline: "2025-11-10", stipend: "$7,000 prize", location: "Online" },
  { id: 68, title: "AR/VR Builders Hack", type: "Hackathon", org: "MetaVerse Labs", skills: ["Unity", "3D Modeling", "C++", "Computer Vision"], deadline: "2025-11-20", stipend: "$18,000 prize", location: "Online" },
  { id: 69, title: "NLP Challenge 2025", type: "Hackathon", org: "NLPHub", skills: ["Python", "Machine Learning", "TensorFlow", "Research"], deadline: "2025-11-28", stipend: "$22,000 prize", location: "Online" },
  { id: 70, title: "Startup Weekend", type: "Hackathon", org: "Techstars", skills: ["Entrepreneurship", "Product Management", "Marketing", "Strategy"], deadline: "2025-12-05", stipend: "$5,000 prize", location: "Various Cities" },
  { id: 71, title: "Design for Impact", type: "Hackathon", org: "ImpactHub", skills: ["Graphic Design", "UI/UX Design", "Branding", "Problem Solving"], deadline: "2025-12-10", stipend: "$9,500 prize", location: "Online" },
  { id: 72, title: "Cloud Architects Challenge", type: "Hackathon", org: "AWS", skills: ["AWS", "Cloud Computing", "Docker", "DevOps"], deadline: "2025-12-15", stipend: "$40,000 prize", location: "Online" },

  // SCHOLARSHIPS
  { id: 73, title: "Google Women Techmakers Scholarship", type: "Scholarship", org: "Google", skills: ["Leadership", "Computer Science", "Problem Solving", "Communication"], deadline: "2025-08-01", stipend: "$10,000", location: "Global" },
  { id: 74, title: "Adobe Women in Design Scholarship", type: "Scholarship", org: "Adobe", skills: ["Graphic Design", "UI/UX Design", "Creativity", "Photoshop"], deadline: "2025-09-01", stipend: "$5,000", location: "Global" },
  { id: 75, title: "Microsoft Leap Scholarship", type: "Scholarship", org: "Microsoft", skills: ["Leadership", "JavaScript", "Problem Solving", "Teamwork"], deadline: "2025-10-01", stipend: "$7,500", location: "Global" },
  { id: 76, title: "AWS Educate Scholarship", type: "Scholarship", org: "Amazon", skills: ["AWS", "Cloud Computing", "Python", "Research"], deadline: "2025-08-15", stipend: "$3,000", location: "Global" },
  { id: 77, title: "STEM Women Excellence Award", type: "Scholarship", org: "STEM Foundation", skills: ["Research", "Statistics", "Problem Solving", "Leadership"], deadline: "2025-09-15", stipend: "$8,000", location: "US/India" },
  { id: 78, title: "Future Founders Scholarship", type: "Scholarship", org: "Kauffman Foundation", skills: ["Entrepreneurship", "Business Development", "Leadership", "Strategy"], deadline: "2025-10-15", stipend: "$12,000", location: "Global" },
  { id: 79, title: "Women in Finance Scholarship", type: "Scholarship", org: "JPMorgan Chase", skills: ["Finance", "Accounting", "Business Analytics", "Excel"], deadline: "2025-09-30", stipend: "$6,000", location: "US" },
  { id: 80, title: "AI for Women Scholarship", type: "Scholarship", org: "OpenAI", skills: ["Machine Learning", "Python", "Research", "Mathematics"], deadline: "2025-11-01", stipend: "$15,000", location: "Global" },
  { id: 81, title: "Cybersecurity Leaders Scholarship", type: "Scholarship", org: "ISC2", skills: ["Cybersecurity", "Networking", "Research", "Problem Solving"], deadline: "2025-10-20", stipend: "$9,000", location: "Global" },
  { id: 82, title: "UX Research Scholarship", type: "Scholarship", org: "Nielsen Norman", skills: ["Research", "UI/UX Design", "Statistics", "Writing"], deadline: "2025-08-20", stipend: "$4,500", location: "US" },
  { id: 83, title: "Data Science Women Grant", type: "Scholarship", org: "DataKind", skills: ["Data Science", "Python", "Statistics", "Machine Learning"], deadline: "2025-09-05", stipend: "$7,000", location: "Global" },
  { id: 84, title: "SheCode Scholarship", type: "Scholarship", org: "SheCode Foundation", skills: ["JavaScript", "React", "HTML/CSS", "Problem Solving"], deadline: "2025-09-10", stipend: "$3,500", location: "Global" },
  { id: 85, title: "Women Entrepreneurs Grant", type: "Scholarship", org: "SBA", skills: ["Entrepreneurship", "Finance", "Marketing", "Leadership"], deadline: "2025-10-05", stipend: "$20,000", location: "US" },
  { id: 86, title: "Blockchain Women Scholarship", type: "Scholarship", org: "ConsenSys", skills: ["Blockchain", "JavaScript", "Cybersecurity", "Research"], deadline: "2025-11-15", stipend: "$5,500", location: "Global" },
  { id: 87, title: "Leadership Excellence Scholarship", type: "Scholarship", org: "WCF", skills: ["Leadership", "Public Speaking", "Project Management", "Communication"], deadline: "2025-08-25", stipend: "$6,500", location: "Global" },
  { id: 88, title: "Social Impact Design Scholarship", type: "Scholarship", org: "IDEO.org", skills: ["Graphic Design", "UI/UX Design", "Research", "Problem Solving"], deadline: "2025-10-25", stipend: "$8,500", location: "Global" },
  { id: 89, title: "Quantum Computing Scholarship", type: "Scholarship", org: "IBM", skills: ["Physics", "Python", "Research", "Machine Learning"], deadline: "2025-11-30", stipend: "$11,000", location: "Global" },
  { id: 90, title: "Green Tech Scholarship", type: "Scholarship", org: "EchoInnovation", skills: ["Research", "Data Analysis", "Statistics", "Problem Solving"], deadline: "2025-09-25", stipend: "$4,000", location: "Global" },
  { id: 91, title: "Women in Gaming Scholarship", type: "Scholarship", org: "EA Games", skills: ["Unity", "C#", "3D Modeling", "Game Design"], deadline: "2025-10-10", stipend: "$7,500", location: "Global" },
  { id: 92, title: "Marketing Excellence Award", type: "Scholarship", org: "AMA Foundation", skills: ["Marketing", "Business Development", "Research", "Communication"], deadline: "2025-08-05", stipend: "$5,000", location: "US" },
  { id: 93, title: "Open Source Contributor Grant", type: "Scholarship", org: "Linux Foundation", skills: ["Git", "Python", "Linux", "JavaScript"], deadline: "2025-09-20", stipend: "$3,000", location: "Global" },
  { id: 94, title: "Rising Leader Award", type: "Scholarship", org: "Forbes 30U30", skills: ["Entrepreneurship", "Leadership", "Innovation", "Strategy"], deadline: "2025-10-30", stipend: "Recognition + Network", location: "Global" },
  { id: 95, title: "Mobile Dev Excellence Scholarship", type: "Scholarship", org: "Apple", skills: ["Swift", "Xcode", "UI/UX Design", "Problem Solving"], deadline: "2025-11-05", stipend: "$8,000", location: "Global" },
  { id: 96, title: "Research Innovation Grant", type: "Scholarship", org: "NSF", skills: ["Research", "Statistics", "Writing", "Data Analysis"], deadline: "2025-12-01", stipend: "$25,000", location: "US" },
  { id: 97, title: "Women in Cloud Scholarship", type: "Scholarship", org: "CloudGirls", skills: ["Cloud Computing", "AWS", "Python", "DevOps"], deadline: "2025-11-08", stipend: "$4,800", location: "Global" },
  { id: 98, title: "Creative Technology Scholarship", type: "Scholarship", org: "Canva", skills: ["Graphic Design", "Canva", "Branding", "Creative Thinking"], deadline: "2025-09-15", stipend: "$6,000", location: "Global" },
  { id: 99, title: "Women in Robotics Grant", type: "Scholarship", org: "IEEE", skills: ["Python", "C++", "Machine Learning", "Research"], deadline: "2025-10-18", stipend: "$9,500", location: "Global" },
  { id: 100, title: "Content Creator Scholarship", type: "Scholarship", org: "YouTube", skills: ["Video Editing", "Content Creation", "Photography", "Social Media"], deadline: "2025-08-12", stipend: "$5,500", location: "Global" },
  { id: 101, title: "HealthTech Innovation Grant", type: "Scholarship", org: "Mayo Clinic", skills: ["Research", "Data Science", "Python", "Statistics"], deadline: "2025-11-25", stipend: "$13,000", location: "US" },
  { id: 102, title: "Diversity in Tech Scholarship", type: "Scholarship", org: "CodePath", skills: ["JavaScript", "Python", "Leadership", "Communication"], deadline: "2025-12-10", stipend: "$5,000", location: "Global" },
];
